version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "deepracer-reward"
s3_prefix = "deepracer-reward"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"

